package db.dao;

import org.apache.ibatis.annotations.Param;
import org.junit.experimental.categories.Categories;

import java.util.List;

public interface CategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Sep 08 18:03:54 MSK 2021
     */
    long countByExample(db.model.CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Sep 08 18:03:54 MSK 2021
     */
    int deleteByExample(db.model.CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Sep 08 18:03:54 MSK 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Sep 08 18:03:54 MSK 2021
     */
    int insert(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Sep 08 18:03:54 MSK 2021
     */
    int insertSelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Sep 08 18:03:54 MSK 2021
     */
    List<Categories> selectByExample(db.model.CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Sep 08 18:03:54 MSK 2021
     */
    Categories selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Sep 08 18:03:54 MSK 2021
     */
    int updateByExampleSelective(@Param("record") Categories record, @Param("example") db.model.CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Sep 08 18:03:54 MSK 2021
     */
    int updateByExample(@Param("record") Categories record, @Param("example") db.model.CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Sep 08 18:03:54 MSK 2021
     */
    int updateByPrimaryKeySelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Sep 08 18:03:54 MSK 2021
     */
    int updateByPrimaryKey(Categories record);
}
